### ISSUE TITLE
Chybějící a rozpracovaná funkcionalita

### ISSUE THREAD

**Issue by Relickus** [Shiftify/shiftify#33]
- [ ] Comparator pro třídu UserWorkdayWrapper -> řazení záznamů v Rozpis směn osob nejdříve volné pracovníky

- [ ] Implementace obrázků uživatelů (ukládání, pořizování) (+ smazání provizorního ImageID pole)

- [ ] Vyladění zobrazování TimeLineView a její naplnění

- [x] Aktivity Rozpis směn pracovníka: implementovat datepicker (+možná udělat infinite scrollview)

- [x] Vytváření nových plánů šichet

- [x] Dokončení akce přidání vyjímky

- [ ] Neobnovování DB při každým zapnutí (souvisí s DataSeeder)

- [ ] Implementace vývojářských testů 

- [ ] Sjednotit názvosloví (šichta vs. směna)

Viz dokument "Diff s počátečním plánem" zde v zálžoce wiki.

**Comment by thepetas** [comment]
Metoda v tride **UserManager** 
`public WorkDay shiftsForDate(long userId, GregorianCalendar date) throws Exception`
Pokud je sichta napr. 22:00 - 8:00 (sichta probihajici pres pulnoc)

- 1.den (22:00-0:00) metoda tuto sichtu zahrne do WorkDay
- 2.den (0:00-8:00) metoda tuto sichtu nezahrne do WorkDay

**Comment by liferili** [comment]
>Dokončení akce přidání vyjímky
Done in https://github.com/lukaskom/shiftify/commit/4af185c7f1bc98193beab137034c28cd0f195655

**Comment by liferili** [comment]
Rozpis směn pracovníka
Reworked in https://github.com/Shiftify/shiftify/commit/680f2fc5bc05adea587171947e1ed55e33043b6e

**Comment by liferili** [comment]
Vytváření nových plánů šichet
Added in https://github.com/Shiftify/shiftify/commit/803551a6f01020d2e98f5fbfdb214a7dc2340772
