### ISSUE TITLE
Broken menu at user detail

### ISSUE THREAD

**Issue by lukaskom** [Shiftify/shiftify#58]
Go through all and correct them or delete them if they are not usefull.

- [x] Add exception doesn't add it. The form closes without adding an exception when going to the form via this menu.
- [x] Add schedule to user option doesn't work at all.

**Comment by liferili** [comment]
Done in https://github.com/Shiftify/shiftify/commit/afb2777f55618443d3a5f9a909baf753aaa5ab0b
